global:
 resolve_timeout: 1m

route:
 receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: devopstraining17042000@gmail.com
    from: devopstraining17042000@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: devopstraining17042000@gmail.com
    auth_identity: devopstraining17042000@gmail.com
    auth_password: password       # Create a app password in the Gmail, click on Google accountsettings -> security
    send_resolved: true
inhibit_rules:
- source_matchers:
    - severity="critical"
  target_matchers:
    - severity="warning"
  equal: ['alertname']