variable "engine" {}
variable "engine_version" {}
variable "db_user" {}
variable "db_password" {}
variable "name" {}
variable "allocated_storage" {}
variable "db_name" {}
variable "instance_class" {}
variable "backup_retention_period" {}
variable "private_subnets" {}
variable "rds_sg" {}